### ISSUE TITLE
won't install because of rvm issues

### ISSUE THREAD

**Issue by saten** [ballistiq/chef-passenger-nginx#1]
==> default: [2015-08-16T10:58:02+00:00] FATAL: Stacktrace dumped to /var/chef/cache/chef-stacktrace.out
==> default: [2015-08-16T10:58:02+00:00] ERROR: bash[Installing passenger nginx module and nginx from source](passenger-nginx::default line 96) had an error: Mixlib::ShellOut::ShellCommandFailed: Expected process to exit with [0], but received '1'
==> default: ---- Begin output of "bash"  "/tmp/chef-script20150816-4093-x428cs" ----
==> default: STDOUT: Welcome to the Phusion Passenger Nginx module installer, v4.0.53.
==> default:
==> default: This installer will guide you through the entire installation process. It
==> default: shouldn't take more than 5 minutes in total.
==> default:
==> default: Here's what you can expect from the installation process:
==> default:
==> default:  1. This installer will compile and install Nginx with Passenger support.
==> default:  2. You'll learn how to configure Passenger in Nginx.
==> default:  3. You'll learn how to deploy a Ruby on Rails application.
==> default:
==> default: Don't worry if anything goes wrong. This installer will advise you on how to
==> default: solve any problems.
==> default:
==> default: Press Enter to continue, or Ctrl-C to abort.
==> default:
==> default: --------------------------------------------
==> default:
==> default: Which languages are you interested in?
==> default:
==> default: Override selection with --languages.
==> default:
==> default:  ‣ ⬢  Ruby
==> default:    ⬢  Python
==> default:    ⬡  Node.js
==> default:    ⬡  Meteor
==> default:
==> default: --------------------------------------------
==> default:
==> default: Checking for required software...
==> default:
==> default:  \* Checking for C compiler...
==> default:       Found: yes
==> default:       Location: /usr/bin/cc
==> default:  \* Checking for C++ compiler...
==> default:       Found: yes
==> default:       Location: /usr/bin/c++
==> default:  \* Checking for A download tool like 'wget' or 'curl'...
==> default:       Found: yes
==> default:       Location: /usr/bin/wget
==> default:  \* Checking for Curl development headers with SSL support...
==> default:       Found: yes
==> default:       curl-config location: /usr/bin/curl-config
==> default:       Header location: /usr/include/curl/curl.h
==> default:       Version: libcurl 7.35.0
==> default:       Usable: yes
==> default:       Supports SSL: yes
==> default:  \* Checking for OpenSSL development headers...
==> default:       Found: yes
==> default:       Location: /usr/include/openssl/ssl.h
==> default:  \* Checking for Zlib development headers...
==> default:       Found: yes
==> default:       Location: /usr/include/zlib.h
==> default: STDERR: Warning: PATH set to RVM ruby but GEM_HOME and/or GEM_PATH not set, see:
==> default:     https://github.com/wayneeseguin/rvm/issues/3212
==> default:
==> default: Hint: To fix PATH errors try using 'rvmsudo' instead of 'sudo', see:
==> default:     http://stackoverflow.com/questions/27784961/received-warning-message-path-set-to-rvm-after-updating-ruby-version-using-rvm/28080063#28080063
==> default:
==> default: Unable to autodetect the currently active RVM gem set name. This could happen if you ran this program using 'sudo' instead of 'rvmsudo'. When using RVM, you're always supposed to use 'rvmsudo' instead of 'sudo!'.
==> default:
==> default: Please try rerunning this program using 'rvmsudo'. If that doesn't help, please contact this program's author for support.

**Comment by leonardteo** [comment]
Hi,

What OS and version did you run this on? On what provider (EC2, Linode, etc)?

Thanks

Leo

**Comment by saten** [comment]
it was ubuntu 14.04 x64 on a bare metal server by softlayer

**Comment by wesguirra** [comment]
Same here some update?

**Comment by leonardteo** [comment]
Sorry guys I don’t know how to fix this. 

1. Due to life, I can not support this. It’s provided “as is”. I’m just sharing this because it’s been useful for me but your mileage may vary. It works on my bare metal servers that I provision for a number of projects.

2. I’ll update the readme to make it clear that this is unsupported. Sorry guys.

**Comment by wesguirra** [comment]
Thank you!
